table 'Line Items'

	measure 'Total Line Item Spend' = SUM('Line Items'[line_total])
		formatString: $#,##0.00

	measure 'Line Item Count' = COUNTROWS('Line Items')

	column invoice_number
		dataType: string
		summarizeBy: none
		sourceColumn: invoice_number

	column line_number
		dataType: int64
		summarizeBy: none
		sourceColumn: line_number

	column description
		dataType: string
		summarizeBy: none
		sourceColumn: description

	column quantity
		dataType: decimal
		summarizeBy: sum
		sourceColumn: quantity

	column unit_price
		dataType: decimal
		formatString: $#,##0.00
		summarizeBy: average
		sourceColumn: unit_price

	column line_total
		dataType: decimal
		formatString: $#,##0.00
		summarizeBy: sum
		sourceColumn: line_total

	partition 'Line Items' = entity
		mode: directLake
		source
			entityName: gold_fact_line_items
			schemaName: dbo
			expressionSource: DatabaseQuery

